ALTER TABLE rentals ADD COLUMN IF NOT EXISTS damage_waiver_opted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS damage_waiver_fee DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS theft_protection_acknowledged BOOLEAN NOT NULL DEFAULT false;
