ALTER TABLE items ADD COLUMN IF NOT EXISTS seller_type VARCHAR(1) DEFAULT 'B' CHECK (seller_type IN ('A', 'B'));
ALTER TABLE items ADD COLUMN IF NOT EXISTS resell_value DECIMAL(10,2);
ALTER TABLE items ADD COLUMN IF NOT EXISTS recovered_amount DECIMAL(10,2) DEFAULT 0;
